export const AllWords = {
    "apple": "سیب",
    "book": "کتاب",
    "car": "گاڑی",
    "dog": "کتا",
    "elephant": "ہاتھی",
    "flower": "پھول",
    "gold": "سونا",
    "house": "گھر",
    "ice": "برف",
    "jungle": "جنگل",
    "kite": "پتنگ",
    "lion": "شیر",
    "moon": "چاند",
    "night": "رات",
    "orange": "مالٹا",
    "pen": "قلم",
    "queen": "ملکہ",
    "river": "دریا",
    "sun": "سورج",
    "tree": "درخت",
    "umbrella": "چھتری",
    "violin": "وائلن",
    "water": "پانی",
    "xylophone": "زیلوفون",
    "yarn": "دھاگہ",
    "zebra": "زیبرا",
    "ant": "چیونٹی",
    "banana": "کیلا",
    "cat": "بلی",
    "door": "دروازہ",
    "egg": "انڈا",
    "fish": "مچھلی",
    "grape": "انگور",
    "hat": "ٹوپی",
    "iron": "لوہا",
    "jug": "مٹکا",
    "king": "بادشاہ",
    "lamp": "چراغ",
    "nest": "گھونسلا",
    "ocean": "سمندر",
    "parrot": "طوطا",
    "question": "سوال",
    "rain": "بارش",
    "snake": "سانپ",
    "tiger": "چیتا",
    "universe": "کائنات",
    "village": "گاؤں",
    "window": "کھڑکی",
    "yogurt": "دہی",
    "zero": "صفر",
    "earth": "زمین",
    "fire": "آگ",
    "globe": "دنیا",
    "hill": "پہاڑی",
    "island": "جزیرہ",
    "jewel": "جواہر",
    "knowledge": "علم",
    "lake": "جھیل",
    "mountain": "پہاڑ",
    "net": "جال",
    "octopus": "آکٹوپس",
    "pencil": "پنسل",
    "quill": "پر",
    "rocket": "راکٹ",
    "school": "اسکول",
    "telescope": "دوربین",
    "unicorn": "یونیکورن",
    "volcano": "آتش فشاں",
    "whale": "وہیل",
    "x-ray": "ایکس رے",
    "yard": "صحن",
    "zoo": "چڑیا گھر",
    "artist": "فنکار",
    "bicycle": "سائیکل",
    "clock": "گھڑی",
    "diamond": "ہیرا",
    "eagle": "عقاب",
    "farmer": "کسان",
    "garden": "باغ",
    "hammer": "ہتھوڑا",
    "insect": "کیڑا",
    "jacket": "جیکٹ",
    "kangaroo": "کینگرو",
    "lantern": "لالٹین",
    "mirror": "آئینہ",
    "newspaper": "اخبار",
    "octagon": "آٹھ کونہ",
    "pyramid": "اہرام",
    "quilt": "رضائی",
    "robot": "روبوٹ",
    "scissors": "قینچی",
    "tunnel": "سرنگ",
    "utensil": "برتن",
    "valley": "وادی",
    "whistle": "سیٹی",
    "xenon": "زینون",
    "yacht": "جہاز",
    "zephyr": "ہلکی ہوا",
    "guitar": "گٹار",
    "piano": "پیانو",
    "drum": "ڈھول",
    "flute": "بانسری",
    "trumpet": "ترہی",
    "saxophone": "سیکسوفون",
    "harp": "باجا",
    "cello": "سیلو",
    "accordion": "ایکورڈین",
    "bongo": "بونگو",
    "clarinet": "کلارنیٹ",
    "oboe": "اوبو",
    "ukulele": "اوکیلیلی",
    "banjo": "بنجو",
    "trombone": "ٹرمبون",
    "harmonica": "ہارمونیکا",
    "sitar": "ستار",
    "tabla": "طبلا",
    "mandolin": "مینڈولین",
    "keyboard": "کی بورڈ",
    "synthesizer": "سنتھیسائزر",
    "bagpipes": "بیگ پائپس",
    "kazoo": "کازو",
    "lyre": "لائر",
    "didgeridoo": "ڈیجریڈو",
    "maracas": "ماراکاس",
    "theremin": "تھیریمین",
    "bass": "باس",
    "gong": "گونگ",
    "cymbals": "جھانجھ",
    "triangle": "تکون",
    "conga": "کانگا",
    "dulcimer": "ڈلسیمر",
    "lute": "لٹ",
    "ocarina": "اوکارینا",
    "sousaphone": "سوسافون",
    "steel drum": "سٹیل ڈرم",
    "vibraphone": "وائبرافون",
    "zither": "زتھر",
    "fiddle": "فڈل",
    "melodica": "میلوڈیکا",
    "glockenspiel": "گلوکنسپیل",
    "bassoon": "بیسون",
    "piccolo": "پیکولو",
    "pan flute": "پین فلوت",
    "shofar": "شوفار",
    "bugle": "بگل",
    "hurdy-gurdy": "ہرڈی گڑڈی",
    "bansuri": "بانسری",
    "erhu": "ایرہو",
    "guqin": "گوقن",
    "sarangi": "سرنگی",
    "shehnai": "شہنائی",
    "koto": "کوٹو",
    "pipa": "پیپا",
    "morin khuur": "مورین خور",
    "djembe": "جمبے",
    "hang drum": "ہینگ ڈرم",
    "tar": "تار",
    "setar": "سیتار",
    "rabab": "رباب",
    "dan bau": "ڈان باؤ",
    "santoor": "سنتور",
    "mbira": "مبیرہ",
    "berimbau": "بیرمباؤ",
    "gayageum": "گایاگیم",
    "kamancheh": "کمانچہ",
    "yangqin": "یانگقین",
    "shamisen": "شامیسن",
    "kobza": "کوبزا",
    "domra": "ڈومرا",
    "tres": "ٹریس",
    "vihuela": "ویہویلا",
    "cuatro": "کواترو",
    "charango": "چارنگو",
    "bandoneon": "بندونیون",
    "flamenco guitar": "فلیمینکو گٹار",
    "bouzouki": "بوزوکی",
    "oud": "عود",
    "cavaquinho": "کاواکینو",
    "nyckelharpa": "نیکل ہارپا",
    "guzheng": "گوزینگ",
    "saz": "ساز",
    "balalaika": "بالالائیکا",
    "laouto": "لاؤٹو",
    "dombyra": "ڈومبیرا",
    "planet": "سیارہ",
    "galaxy": "کہکشاں",
    "asteroid": "کشودرگرہ",
    "meteor": "شہابیہ",
    "comet": "دمدار ستارہ",
    "orbit": "مدار",
    "nebula": "نیبولا",
    "cosmos": "کائنات",
    "black hole": "سیاہ سوراخ",
    "quasar": "کوازر",
    "supernova": "سپرنووا",
    "astronomy": "فلکیات",
    "gravity": "کشش ثقل",
    "light year": "نوری سال",
    "solar system": "شمسی نظام",
    "exoplanet": "غیر شمسی سیارہ",
    "milky way": "دودھیا کہکشاں",
    "pulsar": "پلسار",
    "satellite": "سیٹلائٹ",
    "spaceship": "خلائی جہاز",
    "cosmonaut": "خلاباز",
    "astronaut": "خلا نورد",
    "space station": "خلائی اسٹیشن",
    "lunar": "قمری",
    "martian": "مریخی",
    "interstellar": "بین النجمی",
    "extraterrestrial": "غیر زمینی",
    "wormhole": "ورم ہول",
    "big bang": "بگ بینگ",
    "dark matter": "تاریک مادہ",
    "dark energy": "تاریک توانائی",
    "cosmic rays": "کائناتی شعاعیں",
    "event horizon": "واقعاتی افق",
    "red giant": "سرخ دیو",
    "white dwarf": "سفید بونا",
    "neutron star": "نیوٹران ستارہ",
    "singularity": "اکیلائیت",
    "gravity wave": "ثقل موج",
    "extragalactic": "بین کہکشانی",
    "moon base": "چاندی اڈہ",
    "space probe": "خلائی تحقیق",
    "solar flare": "شمسی شعلہ",
    "planetary ring": "سیاروی انگوٹھی",
    "gamma ray burst": "گاما رے دھماکہ",
    "terraforming": "ارض سازی",
    "habitable zone": "رہائشی زون",
    "star cluster": "ستارہ جھرمٹ",
    "black dwarf": "سیاہ بونا",
    "brown dwarf": "بھورا بونا",
    "celestial body": "آسمانی جسم",
    "cosmic web": "کائناتی جال",
    "observable universe": "مشاہداتی کائنات",
    "spaghettification": "اسپاگھیٹیفیکیشن",
    "zero gravity": "صفر کشش ثقل",
    "space junk": "خلائی ملبہ",
    "solar eclipse": "سورج گرہن",
    "lunar eclipse": "چاند گرہن",
    "astronomical unit": "فلکیاتی اکائی",
    "planetary nebula": "سیاروی نیبولا",
    "hypernova": "ہائپرنووا",
    "stellar wind": "ستاروی ہوا",
    "perihelion": "حضیض شمسی",
    "aphelion": "اوج شمسی",
    "light pollution": "نوری آلودگی",
    "gravitational lensing": "ثقالتی عدسہ کاری",
    "exozodiacal light": "غیر شمسی زودیاکل روشنی",
    "tidal force": "مد و جزر قوت",
    "cosmic inflation": "کائناتی پھیلاؤ",
    "dark flow": "تاریک بہاؤ",
    "multiverse": "کثیر کائنات",
    "quantum entanglement": "کوانٹم الجھن",
    "time dilation": "وقت توسیع",
    "stellar nursery": "ستارہ نرسری",
    "heliosphere": "شمسی کرہ",
    "van allen belt": "وان ایلن پٹی",
    "exobiology": "غیر زمینی حیاتیات",
    "astrophysics": "فلکی طبیعیات",
    "heliocentric": "شمسی مرکزیت",
    "geocentric": "زمینی مرکزیت",
    "planetary defense": "سیاروی دفاع",
    "celestial navigation": "آسمانی نیویگیشن",
    "asteroid belt": "کشودرگرہ پٹی",
    "lunar rover": "قمری گاڑی",
    "space mining": "خلائی کان کنی",
    "cryovolcano": "برفیلی آتش فشاں",
    "solar wind": "شمسی ہوا",
    "star formation": "ستارہ تشکیل",
    "exoplanet atmosphere": "غیر شمسی سیاروی فضا",
    "stellar explosion": "ستاروی دھماکہ",
    "fast radio burst": "تیز ریڈیو دھماکہ",
    "hubble constant": "ہبل مستقل",
    "cosmic background radiation": "کائناتی پس منظر تابکاری",
    "plasma physics": "پلازما طبیعیات",
    "light speed": "روشنی کی رفتار",
    "orbital resonance": "مداری ہم آہنگی",
    "gravitational collapse": "ثقالتی انہدام",
    "rover exploration": "خلائی گاڑی تحقیق",
    "exoplanetary system": "غیر شمسی سیاروی نظام",
    "stellar evolution": "ستاروی ارتقا"
  };
  